#!/usr/bin/env python
"""What `phase_locked`'s fallback actually buys, on both objectives at once.

`phase_locked` parks on a predicted beam arrival and runs a fallback policy the
rest of the time -- which is most of the episode, so the fallback dominates its
score. The shipped default is `whittle`. `coprime_sweep` was added as an option
after noticing that on HARD it took never-intercepted from 27 to 16 over four
seeds, a 41% improvement, and that looked like a free upgrade.

It is not free, and this script is why the default did not change. Measured
over ten paired seeds per tier, the sweep fallback trades one named objective
for the other:

    easy     intercept time -83.6%   interception rate -49.2%   dominated
    medium   intercept time +11.2%   interception rate -68.1%   trade
    hard     intercept time +19.8%   interception rate -66.8%   trade

On EASY it is worse at everything: coverage is already free there -- both modes
reach zero never-intercepted -- so slots spent sweeping buy nothing and the
lost collection is pure cost. On MEDIUM and HARD coverage binds, and the sweep
fallback genuinely improves intercept time and completeness while giving up
collection depth. That is a mission decision, not a bug, so both modes ship and
neither is called "best".

The pattern is the same one in ``tier_policy.md``: as emitter density rises,
the optimum shifts from exploitation toward coverage.

Usage::

    python scripts/phase_locked_modes.py                 # render cached results
    python scripts/phase_locked_modes.py --measure --n-seeds 10
"""

from __future__ import annotations

import argparse
import contextlib
import json
import sys
from pathlib import Path

import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

for _stream in (sys.stdout, sys.stderr):
    with contextlib.suppress(AttributeError, ValueError):
        _stream.reconfigure(encoding="utf-8", errors="replace")

REPORTS = REPO_ROOT / "reports"
TIERS = ("easy", "medium", "hard")
MODES = ("whittle", "coprime_sweep")


def measure(n_seeds: int) -> dict:
    """Run both fallback modes on identical episodes, per tier."""
    from smartscan.agents import build_agent
    from smartscan.analysis.metrics import evaluate_episode
    from smartscan.config import load_config
    from smartscan.env.rf_environment import build_episode, generate_scenario
    from smartscan.hal.simulated import detection_probability_tensor
    from smartscan.runner import run_episode

    out: dict = {}
    for tier in TIERS:
        base = load_config(f"{tier}.yaml")
        eps = []
        for i in range(n_seeds):
            seed = base.run.seed + i
            scenario = generate_scenario(seed, config=base)
            episode = build_episode(scenario)
            eps.append((seed, scenario, episode,
                        detection_probability_tensor(episode, base)))
        out[tier] = {}
        for mode in MODES:
            cfg = load_config(f"{tier}.yaml", {"agents.phase_locked.fallback": mode})
            ttfi, twir, never = [], [], []
            for seed, scenario, episode, pd_tensor in eps:
                r = run_episode(cfg, seed,
                                build_agent("phase_locked", cfg, seed, scenario),
                                scenario=scenario, episode=episode)
                m = evaluate_episode(r, cfg, pd_tensor)
                ttfi.append(float(m.get("ttfi_median_s", np.nan)))
                twir.append(float(m.get("twir_rate", np.nan)))
                never.append(int(m.get("n_never_intercepted", 0)))
            out[tier][mode] = {"ttfi": ttfi, "twir": twir, "never": never}
            print(f"  {tier}/{mode}: done", flush=True)
    return out


def render(d: dict) -> str:
    L: list[str] = []
    A = L.append
    A("# `phase_locked`: which fallback, and what it costs")
    A("")
    A("_Generated by `scripts/phase_locked_modes.py`._")
    A("")
    A("`phase_locked` parks on a predicted beam arrival and runs a fallback policy the")
    A("rest of the time. That is most of the episode, so the fallback decides most of")
    A("the score. Both modes ship; neither is universally better.")
    A("")
    A("Relative to the `whittle` default, over paired seeds per tier:")
    A("")
    A("| tier | intercept time | interception rate | never intercepted | verdict |")
    A("|---|---|---|---|---|")
    for tier in TIERS:
        if tier not in d:
            continue
        a, b = d[tier]["whittle"], d[tier]["coprime_sweep"]
        ta, tb = np.nanmedian(a["ttfi"]), np.nanmedian(b["ttfi"])
        wa, wb = np.nanmedian(a["twir"]), np.nanmedian(b["twir"])
        dt = (ta - tb) / ta * 100 if ta else float("nan")
        dw = (wb - wa) / wa * 100 if wa else float("nan")
        dn = sum(b["never"]) - sum(a["never"])
        verdict = ("**dominated** — worse at everything" if dt < 0 and dw < 0
                   else "Pareto trade")
        A(f"| `{tier}` | {dt:+.1f}% | {dw:+.1f}% | {dn:+d} | {verdict} |")
    A("")
    A("**The default stays `whittle`.** Interception rate is an objective the problem")
    A("statement names; never-intercepted is a diagnostic this project added. A change")
    A("that gives up two thirds of the collection rate to improve a diagnostic is not")
    A("an upgrade, and on `easy` the sweep fallback is simply worse at everything --")
    A("coverage is already free there, both modes reach zero never-intercepted, so")
    A("slots spent sweeping buy nothing.")
    A("")
    A("**Use `coprime_sweep` when the mission is to find every emitter once.** On")
    A("`medium` and `hard` it improves intercept time by 11–20% and cuts")
    A("never-intercepted, at the cost of collection depth. Set it with:")
    A("")
    A("```bash")
    A("--set agents.phase_locked.fallback=coprime_sweep")
    A("```")
    A("")
    A("This is the density pattern from `tier_policy.md` again: as emitter density")
    A("rises, the optimum shifts from exploitation toward coverage.")
    A("")
    return "\n".join(L)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--measure", action="store_true",
                    help="Re-run the comparison instead of rendering the cached run.")
    ap.add_argument("--n-seeds", type=int, default=10)
    ap.add_argument("--out", default=str(REPORTS / "phase_locked_modes"))
    args = ap.parse_args()

    stem = Path(args.out)
    if args.measure:
        data = measure(args.n_seeds)
        stem.with_suffix(".json").write_text(json.dumps(data, indent=1), encoding="utf-8")
    else:
        p = stem.with_suffix(".json")
        if not p.is_file():
            raise SystemExit(f"no cached run at {p}; pass --measure")
        data = json.loads(p.read_text(encoding="utf-8"))

    stem.with_suffix(".md").write_text(render(data), encoding="utf-8")
    print(render(data))
    print(f"wrote {stem.with_suffix('.md')}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
