#!/usr/bin/env python
"""Which scheduler to fly on which tier, and why the answer changes.

There is no single best scheduler here, and saying so is not a hedge -- the
optimum moves with emitter density, in a direction the physics predicts.

A receiver seeing ``K`` of ``B`` channels can cover the band on a fixed
revisit period. Whether that is enough depends on how many emitters have to be
found in it. On EASY, five emitters, coverage is nearly free: every sweep and
every bandit reaches zero never-intercepted, so the coverage constraint is
slack and the whole slot budget can be spent on exploitation -- which is why
``ppo`` and ``predictor`` reach TWIR an order of magnitude above the sweep.
On HARD, thirty emitters with five decoys, coverage is the binding constraint,
and every slot the predictor takes is a slot removed from finding an emitter
nobody has seen yet. There, the plain sweep wins and every learned policy
loses in proportion to how much of the schedule it controls.

So the recommendation is a frontier, not a winner. For each tier this reports
the Pareto-optimal policies over (never-intercepted, TWIR): the ones where you
cannot improve one without giving up the other. Which point on that frontier
to fly is a mission decision -- find everything once, or collect as much as
possible from what you have found -- not something a benchmark can settle.

Reads the shipped ``reports/metrics_{tier}.json``; writes
``reports/tier_policy.{md,json}``.
"""

from __future__ import annotations

import argparse
import collections
import contextlib
import json
import sys
from pathlib import Path

import numpy as np

# The report uses arrows and em dashes; a Windows console defaults to cp1252
# and raises UnicodeEncodeError on them, killing the script after the files are
# already written. The terminal's encoding should not decide whether this runs.
for _stream in (sys.stdout, sys.stderr):
    with contextlib.suppress(AttributeError, ValueError):
        _stream.reconfigure(encoding="utf-8", errors="replace")

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))
REPORTS = REPO_ROOT / "reports"
TIERS = ("easy", "medium", "hard")


def _aggregate(tier: str) -> dict[str, dict[str, float]]:
    """Per-agent summary across seeds for one tier."""
    rows = json.loads((REPORTS / f"metrics_{tier}.json").read_text(encoding="utf-8"))["rows"]
    by: dict[str, list[dict]] = collections.defaultdict(list)
    for r in rows:
        by[r["agent"]].append(r)

    def med(rs, key):
        xs = [r.get(key) for r in rs
              if isinstance(r.get(key), (int, float)) and np.isfinite(r.get(key))]
        return float(np.median(xs)) if xs else float("nan")

    out = {}
    for agent, rs in by.items():
        out[agent] = {
            "n_seeds": len(rs),
            # Summed, not averaged: it is a count of emitters, and the total
            # over the grid is what the leaderboard reports.
            "never_intercepted": float(sum(r.get("n_never_intercepted", 0) for r in rs)),
            "twir": med(rs, "twir_rate"),
            "ttfi_s": med(rs, "ttfi_median_s"),
            "coverage": med(rs, "coverage"),
            "reward": med(rs, "reward_total"),
        }
    return out


def _pareto(agents: dict[str, dict[str, float]]) -> list[str]:
    """Agents not dominated on (never-intercepted down, TWIR up)."""
    keep = []
    for a, va in agents.items():
        if not np.isfinite(va["twir"]):
            continue
        dominated = any(
            b != a
            and np.isfinite(vb["twir"])
            and vb["never_intercepted"] <= va["never_intercepted"]
            and vb["twir"] >= va["twir"]
            and (vb["never_intercepted"] < va["never_intercepted"] or vb["twir"] > va["twir"])
            for b, vb in agents.items()
        )
        if not dominated:
            keep.append(a)
    return sorted(keep, key=lambda a: agents[a]["never_intercepted"])


def render(data: dict) -> str:
    L: list[str] = []
    A = L.append
    A("# Which scheduler for which tier")
    A("")
    A("_Generated by `scripts/tier_policy.py` from the shipped benchmark._")
    A("")
    A("The optimum moves with emitter density, and it moves in the direction the")
    A("physics predicts. A receiver seeing `K` of `B` channels covers the band on a")
    A("fixed revisit period; whether that suffices depends on how many emitters must")
    A("be found in it.")
    A("")
    A("- **EASY** — 5 emitters. Coverage is nearly free: every sweep and bandit reaches")
    A("  zero never-intercepted, so the constraint is slack and the slot budget can go")
    A("  to exploitation.")
    A("- **MEDIUM** — 15 emitters. The constraint starts to bind; the frontier has a")
    A("  real trade-off along it.")
    A("- **HARD** — 30 emitters, 5 decoys. Coverage is the binding constraint. Every")
    A("  slot a predictor takes is a slot not spent finding an emitter nobody has seen,")
    A("  and emitter channels are drawn uniformly at random, so before first contact")
    A("  there is nothing to predict.")
    A("")
    for tier in data["tiers"]:
        d = data["tiers"][tier]
        A(f"## `{tier}`")
        A("")
        A("| scheduler | never intercepted | TWIR | ttfi (s) | coverage |")
        A("|---|---|---|---|---|")
        for a in d["pareto"]:
            v = d["agents"][a]
            A(f"| **`{a}`** | {v['never_intercepted']:.0f} | {v['twir']:.5f} | "
              f"{v['ttfi_s']:.4f} | {v['coverage']:.3f} |")
        A("")
        A(f"_Pareto-optimal over (never-intercepted, TWIR) from {len(d['agents'])} "
          f"schedulers, {d['n_seeds']} seeds. Everything else is beaten on both axes._")
        A("")
        A(f"- **Find everything once** → `{d['best_coverage']}` "
          f"({d['agents'][d['best_coverage']]['never_intercepted']:.0f} never intercepted)")
        A(f"- **Collect the most from what is found** → `{d['best_twir']}` "
          f"(TWIR {d['agents'][d['best_twir']]['twir']:.5f}, "
          f"{d['agents'][d['best_twir']]['never_intercepted']:.0f} never intercepted)")
        cov, twir = d["best_coverage"], d["best_twir"]
        if cov == twir:
            A(f"- Both at once: `{cov}` dominates on this tier.")
        else:
            dn = d["agents"][twir]["never_intercepted"] - d["agents"][cov]["never_intercepted"]
            ratio = (d["agents"][twir]["twir"] / d["agents"][cov]["twir"]
                     if d["agents"][cov]["twir"] else float("nan"))
            A(f"- The price of the swap: **{dn:+.0f} emitters never intercepted** "
              f"for **{ratio:.1f}x the TWIR**.")
        A("")
    A("## Reading this as one strategy")
    A("")
    A("The pattern across tiers is the actual result: **as emitter density rises, the")
    A("optimal policy shifts from exploitation to coverage.** That is a scan strategy")
    A("that adapts to the environment rather than a fixed schedule, which is what the")
    A("problem statement asks for -- and the switch can be driven online, since the")
    A("count of distinct emitters found in the first second is an observable the")
    A("receiver already has.")
    A("")
    return "\n".join(L)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", default=str(REPORTS / "tier_policy"))
    args = ap.parse_args()

    data: dict = {"tiers": {}}
    for tier in TIERS:
        if not (REPORTS / f"metrics_{tier}.json").is_file():
            continue
        agents = _aggregate(tier)
        front = _pareto(agents)
        usable = {a: v for a, v in agents.items() if np.isfinite(v["twir"])}
        data["tiers"][tier] = {
            "agents": agents,
            "pareto": front,
            "n_seeds": max(v["n_seeds"] for v in agents.values()),
            # Tie-break on TWIR. Ten schedulers reach zero never-intercepted on
            # EASY; recommending whichever sorts first would name `sequential`
            # when `epsilon_greedy` matches its zero at 3.7x the TWIR and
            # strictly dominates it. A tie on the primary axis is decided by the
            # secondary one, not by dictionary order.
            "best_coverage": min(
                usable, key=lambda a: (usable[a]["never_intercepted"], -usable[a]["twir"])),
            "best_twir": max(usable, key=lambda a: usable[a]["twir"]),
        }
    if not data["tiers"]:
        print("no reports/metrics_*.json -- run `make benchmark` first", file=sys.stderr)
        return 1

    stem = Path(args.out)
    stem.parent.mkdir(parents=True, exist_ok=True)
    stem.with_suffix(".json").write_text(json.dumps(data, indent=1, default=float),
                                         encoding="utf-8")
    stem.with_suffix(".md").write_text(render(data), encoding="utf-8")
    print(render(data))
    print(f"wrote {stem.with_suffix('.md')} and {stem.with_suffix('.json')}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
